
package com.elektra.uniformes.comercio.cron.dao.clienteWS.ConsultaPedidoAbasto;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "intfPED_CENT_CONSULTA_STATUS-service", targetNamespace = "http://servicios.elektra.com.mx/ekt/1.0/ws_ped_cent_consulta_uniformes", wsdlLocation = "WS_PED_CENT_CONSULTA_UNIFORMES.wsdl")
public class IntfPEDCENTCONSULTASTATUSService
    extends Service
{

    private final static URL INTFPEDCENTCONSULTASTATUSSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTFPEDCENTCONSULTASTATUSSERVICE_EXCEPTION;
    private final static QName INTFPEDCENTCONSULTASTATUSSERVICE_QNAME = new QName("http://servicios.elektra.com.mx/ekt/1.0/ws_ped_cent_consulta_uniformes", "intfPED_CENT_CONSULTA_STATUS-service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/lrodriguez/Downloads/wsimport/inventarios/WS_PED_CENT_CONSULTA_UNIFORMES.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTFPEDCENTCONSULTASTATUSSERVICE_WSDL_LOCATION = url;
        INTFPEDCENTCONSULTASTATUSSERVICE_EXCEPTION = e;
    }


    public IntfPEDCENTCONSULTASTATUSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntfPEDCENTCONSULTASTATUSService() {
        super(INTFPEDCENTCONSULTASTATUSSERVICE_WSDL_LOCATION, new QName("http://servicios.elektra.com.mx/ekt/1.0/ws_ped_cent_consulta_uniformes", "intfPED_CENT_CONSULTA_STATUS-service"));
    }

    /**
     * 
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "intfwsPED_CENT_CONSULTA_STATUSEndpoint0")
    public PortType getIntfwsPEDCENTCONSULTASTATUSEndpoint0() {
        return super.getPort(new QName("http://servicios.elektra.com.mx/ekt/1.0/ws_ped_cent_consulta_uniformes", "intfwsPED_CENT_CONSULTA_STATUSEndpoint0"), PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "intfwsPED_CENT_CONSULTA_STATUSEndpoint0")
    public PortType getIntfwsPEDCENTCONSULTASTATUSEndpoint0(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios.elektra.com.mx/ekt/1.0/ws_ped_cent_consulta_uniformes", "intfwsPED_CENT_CONSULTA_STATUSEndpoint0"), PortType.class, features);
    }

}
