
package com.elektra.uniformes.comercio.cron.dao.clienteWS.ConsultaPedidoAbasto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "portType", targetNamespace = "http://servicios.elektra.com.mx/ekt/1.0/ws_ped_cent_consulta_uniformes")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.elektra.uniformes.comercio.cron.dao.clienteWS.ConsultaPedidoAbasto.Parametros3
     */
    @WebMethod(operationName = "PED__CENT__CONSULTA__STATUS__NEOp", action = "/BusinessProcesses/Systems/WSEvents/intfPED_CENT_CONSULTA_STATUS-service.serviceagent/intfwsPED_CENT_CONSULTA_STATUSEndpoint0/PED__CENT__CONSULTA__STATUS__NEOp")
    @WebResult(name = "Parametros", targetNamespace = "http://esquemas.elektra.com.mx/ekt/1.0/Esq_Salid_Consulta", partName = "parameters")
    public Parametros3 pedCENTCONSULTASTATUSNEOp(
        @WebParam(name = "Entrada", targetNamespace = "http://esquemas.elektra.com.mx/ekt/1.0/Esq_Entr_Consulta", partName = "parameters")
        Entrada parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.elektra.uniformes.comercio.cron.dao.clienteWS.ConsultaPedidoAbasto.Parametros
     */
    @WebMethod(operationName = "PED__CENT__CONSULTA__UNIFORMESOp", action = "/BusinessProcesses/Systems/WSEvents/intfPED_CENT_CONSULTA_STATUS-service.serviceagent/intfwsPED_CENT_CONSULTA_STATUSEndpoint0/PED__CENT__CONSULTA__UNIFORMESOp")
    @WebResult(name = "Parametros", targetNamespace = "http://esquemas.elektra.com.mx/ekt/1.0/Esq_Salid_Ped_Cent_Consul_Uniformes", partName = "parameters")
    public Parametros pedCENTCONSULTAUNIFORMESOp(
        @WebParam(name = "Parametros_Entrada", targetNamespace = "http://esquemas.elektra.com.mx/ekt/1.0/Esq_Entr_Ped_Cent_Consul_Uniformes", partName = "parameters")
        ParametrosEntrada parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.elektra.uniformes.comercio.cron.dao.clienteWS.ConsultaPedidoAbasto.Parametros
     */
    @WebMethod(operationName = "PED__CENT__CONSULTA__STATUSOp", action = "/BusinessProcesses/Systems/WSEvents/intfPED_CENT_CONSULTA_STATUS-service.serviceagent/intfwsPED_CENT_CONSULTA_STATUSEndpoint0/PED__CENT__CONSULTA__STATUSOp")
    @WebResult(name = "Parametros", targetNamespace = "http://esquemas.elektra.com.mx/ekt/1.0/Esq_Salid_Ped_Cent_Consul_Uniformes", partName = "parameters")
    public Parametros pedCENTCONSULTASTATUSOp(
        @WebParam(name = "Parametros_Entrada", targetNamespace = "http://esquemas.elektra.com.mx/ekt/1.0/Esq_Entr_Uniformes_Status", partName = "parameters")
        ParametrosEntrada2 parameters);

}
