
package com.elektra.uniformes.comercio.cron.dao.clienteWS.GrabaPedidoAbasto;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "intfWS_VTA_MAYOREO-service", targetNamespace = "http://xmlns.example.com/1379022754225", wsdlLocation = "file:/C:/DATOS/proyectos%20C3/UniformesComercio/meta/wsdl%20abasto%20prod/WS_VTA_MAYOREO.wsdl")
public class IntfWSVTAMAYOREOService
    extends Service
{

    private final static URL INTFWSVTAMAYOREOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.elektra.uniformes.comercio.cron.dao.clienteWS.GrabaPedidoAbasto.IntfWSVTAMAYOREOService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.elektra.uniformes.comercio.cron.dao.clienteWS.GrabaPedidoAbasto.IntfWSVTAMAYOREOService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/DATOS/proyectos%20C3/UniformesComercio/meta/wsdl%20abasto%20prod/WS_VTA_MAYOREO.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/DATOS/proyectos%20C3/UniformesComercio/meta/wsdl%20abasto%20prod/WS_VTA_MAYOREO.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTFWSVTAMAYOREOSERVICE_WSDL_LOCATION = url;
    }

    public IntfWSVTAMAYOREOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntfWSVTAMAYOREOService() {
        super(INTFWSVTAMAYOREOSERVICE_WSDL_LOCATION, new QName("http://xmlns.example.com/1379022754225", "intfWS_VTA_MAYOREO-service"));
    }

    /**
     * 
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "intfwsWS_VTA_MAYOREOEndpoint3")
    public PortType getIntfwsWSVTAMAYOREOEndpoint3() {
        return super.getPort(new QName("http://xmlns.example.com/1379022754225", "intfwsWS_VTA_MAYOREOEndpoint3"), PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "intfwsWS_VTA_MAYOREOEndpoint3")
    public PortType getIntfwsWSVTAMAYOREOEndpoint3(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1379022754225", "intfwsWS_VTA_MAYOREOEndpoint3"), PortType.class, features);
    }

}
