DROP TABLE TANOTASCARGOENTRADA CASCADE CONSTRAINTS;

DROP TABLE TATIPOTALLA CASCADE CONSTRAINTS;

DROP TABLE TATIPOKIT CASCADE CONSTRAINTS;

DROP TABLE TACARGASSEMESTRALES CASCADE CONSTRAINTS;

DROP TABLE TABITACORASOLICITUD CASCADE CONSTRAINTS;

DROP TABLE TACANTIDADES CASCADE CONSTRAINTS;

DROP TABLE TACARGASXNEGOCIO CASCADE CONSTRAINTS;

DROP TABLE TADIASSPPI CASCADE CONSTRAINTS;

DROP TABLE TADISTRIBUCIONSPPI CASCADE CONSTRAINTS;

DROP TABLE TAEMPLEADOSADMINISTRADOR CASCADE CONSTRAINTS;

DROP TABLE TAEQUIVALENCIACANALES CASCADE CONSTRAINTS;

DROP TABLE TAESTATUSPEDIDOS CASCADE CONSTRAINTS;

DROP TABLE TAESTATUSSPPI CASCADE CONSTRAINTS;

DROP TABLE TAFUNCIONESXNEGOCIO CASCADE CONSTRAINTS;

DROP TABLE TAGENERO CASCADE CONSTRAINTS;

DROP TABLE TAMENUS CASCADE CONSTRAINTS;

DROP TABLE TAMENUSFUNCIONESXNEGOCIO CASCADE CONSTRAINTS;

DROP TABLE TANEGOCIOS CASCADE CONSTRAINTS;

DROP TABLE TAPRECIOS CASCADE CONSTRAINTS;

DROP TABLE TAPRENDAS  CASCADE CONSTRAINTS;

DROP TABLE TAREMISIONESXPEDIDO CASCADE CONSTRAINTS;

DROP TABLE TASKUSXKIT CASCADE CONSTRAINTS;

DROP TABLE TASOLICITUDES CASCADE CONSTRAINTS;

DROP TABLE TASOLICITUDESDETALLE CASCADE CONSTRAINTS;

DROP TABLE TASOLICITUDESXCARGA CASCADE CONSTRAINTS;

DROP TABLE TATALLASXTIPOPRENDA CASCADE CONSTRAINTS;

DROP TABLE TATIENDAS CASCADE CONSTRAINTS;

DROP TABLE TATIENDASDIRIP CASCADE CONSTRAINTS;

DROP TABLE TATIPOCALCULOPRECIO CASCADE CONSTRAINTS;

DROP TABLE TATIPOSERROR CASCADE CONSTRAINTS;

DROP TABLE TATIPOSOLICITUD CASCADE CONSTRAINTS;

DROP TABLE TATIPOSPRENDA CASCADE CONSTRAINTS;

DROP TABLE TATIPOSPRENDAXKIT CASCADE CONSTRAINTS;

DROP TABLE TAESTATUSEMPLEADOADMIN CASCADE CONSTRAINTS;

DROP TABLE TADESCUENTOSSAPXPEDIDO CASCADE CONSTRAINTS;

DROP TABLE TADISTRIBUCIONSAP CASCADE CONSTRAINTS;