
package com.elektra.uniformes.comercio.cron.dao.clienteWS.SPPI2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ConectorUnicoPort", targetNamespace = "http://conectorunico.com.mx/definitions")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConectorUnicoPort {


    /**
     * 
     * @param consultaServiciosRequest
     * @return
     *     returns SPP2.ConsultaServiciosResponse
     */
    @WebMethod
    @WebResult(name = "consultaServiciosResponse", targetNamespace = "http://conectorunico/schemas", partName = "consultaServiciosResponse")
    public ConsultaServiciosResponse consultaServicios(
        @WebParam(name = "consultaServiciosRequest", targetNamespace = "http://conectorunico/schemas", partName = "consultaServiciosRequest")
        ConsultaServiciosRequest consultaServiciosRequest);

    /**
     * 
     * @param avanceCargaVirtualRequest
     * @return
     *     returns SPP2.AvanceCargaVirtualResponse
     */
    @WebMethod
    @WebResult(name = "avanceCargaVirtualResponse", targetNamespace = "http://conectorunico/schemas", partName = "avanceCargaVirtualResponse")
    public AvanceCargaVirtualResponse avanceCargaVirtual(
        @WebParam(name = "avanceCargaVirtualRequest", targetNamespace = "http://conectorunico/schemas", partName = "avanceCargaVirtualRequest")
        AvanceCargaVirtualRequest avanceCargaVirtualRequest);

    /**
     * 
     * @param verificaSaldoRequest
     * @return
     *     returns SPP2.VerificaSaldoResponse
     */
    @WebMethod
    @WebResult(name = "verificaSaldoResponse", targetNamespace = "http://conectorunico/schemas", partName = "verificaSaldoResponse")
    public VerificaSaldoResponse verificaSaldo(
        @WebParam(name = "verificaSaldoRequest", targetNamespace = "http://conectorunico/schemas", partName = "verificaSaldoRequest")
        VerificaSaldoRequest verificaSaldoRequest);

    /**
     * 
     * @param detalleCargaRealRequest
     * @return
     *     returns SPP2.DetalleCargaRealResponse
     */
    @WebMethod
    @WebResult(name = "detalleCargaRealResponse", targetNamespace = "http://conectorunico/schemas", partName = "detalleCargaRealResponse")
    public DetalleCargaRealResponse detalleCargaReal(
        @WebParam(name = "detalleCargaRealRequest", targetNamespace = "http://conectorunico/schemas", partName = "detalleCargaRealRequest")
        DetalleCargaRealRequest detalleCargaRealRequest);

    /**
     * 
     * @param avanceCargaRealRequest
     * @return
     *     returns SPP2.AvanceCargaRealResponse
     */
    @WebMethod
    @WebResult(name = "avanceCargaRealResponse", targetNamespace = "http://conectorunico/schemas", partName = "avanceCargaRealResponse")
    public AvanceCargaRealResponse avanceCargaReal(
        @WebParam(name = "avanceCargaRealRequest", targetNamespace = "http://conectorunico/schemas", partName = "avanceCargaRealRequest")
        AvanceCargaRealRequest avanceCargaRealRequest);

    /**
     * 
     * @param cargaRealesRequest
     * @return
     *     returns SPP2.CargaRealesResponse
     */
    @WebMethod
    @WebResult(name = "cargaRealesResponse", targetNamespace = "http://conectorunico/schemas", partName = "cargaRealesResponse")
    public CargaRealesResponse cargaReales(
        @WebParam(name = "cargaRealesRequest", targetNamespace = "http://conectorunico/schemas", partName = "cargaRealesRequest")
        CargaRealesRequest cargaRealesRequest);

    /**
     * 
     * @param cargaVirtualesRequest
     * @return
     *     returns SPP2.CargaVirtualesResponse
     */
    @WebMethod
    @WebResult(name = "cargaVirtualesResponse", targetNamespace = "http://conectorunico/schemas", partName = "cargaVirtualesResponse")
    public CargaVirtualesResponse cargaVirtuales(
        @WebParam(name = "cargaVirtualesRequest", targetNamespace = "http://conectorunico/schemas", partName = "cargaVirtualesRequest")
        CargaVirtualesRequest cargaVirtualesRequest);

    /**
     * 
     * @param detalleCargaVirtualRequest
     * @return
     *     returns SPP2.DetalleCargaVirtualResponse
     */
    @WebMethod
    @WebResult(name = "detalleCargaVirtualResponse", targetNamespace = "http://conectorunico/schemas", partName = "detalleCargaVirtualResponse")
    public DetalleCargaVirtualResponse detalleCargaVirtual(
        @WebParam(name = "detalleCargaVirtualRequest", targetNamespace = "http://conectorunico/schemas", partName = "detalleCargaVirtualRequest")
        DetalleCargaVirtualRequest detalleCargaVirtualRequest);

}
