
package com.elektra.uniformes.comercio.cron.dao.clienteWS.SPPI2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ConectorUnicoPortService", targetNamespace = "http://conectorunico.com.mx/definitions", wsdlLocation = "file:/V:/CENTRALdesarrollo_view/desCentralC3/Aplicaciones/UnifOperacion/SRVUniformesComercio/Fuente/DAO/src/main/java/com/elektra/uniformes/comercio/cron/dao/clienteWS/WS_SPPI_2.wsdl")
public class ConectorUnicoPortService
    extends Service
{

    private final static URL CONECTORUNICOPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.elektra.uniformes.comercio.cron.dao.clienteWS.SPPI2.ConectorUnicoPortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.elektra.uniformes.comercio.cron.dao.clienteWS.SPPI2.ConectorUnicoPortService.class.getResource(".");
            url = new URL(baseUrl, "file:/V:/CENTRALdesarrollo_view/desCentralC3/Aplicaciones/UnifOperacion/SRVUniformesComercio/Fuente/DAO/src/main/java/com/elektra/uniformes/comercio/cron/dao/clienteWS/WS_SPPI_2.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/V:/CENTRALdesarrollo_view/desCentralC3/Aplicaciones/UnifOperacion/SRVUniformesComercio/Fuente/DAO/src/main/java/com/elektra/uniformes/comercio/cron/dao/clienteWS/WS_SPPI_2.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONECTORUNICOPORTSERVICE_WSDL_LOCATION = url;
    }

    public ConectorUnicoPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConectorUnicoPortService() {
        super(CONECTORUNICOPORTSERVICE_WSDL_LOCATION, new QName("http://conectorunico.com.mx/definitions", "ConectorUnicoPortService"));
    }

    /**
     * 
     * @return
     *     returns ConectorUnicoPort
     */
    @WebEndpoint(name = "ConectorUnicoPortSoap11")
    public ConectorUnicoPort getConectorUnicoPortSoap11() {
        return super.getPort(new QName("http://conectorunico.com.mx/definitions", "ConectorUnicoPortSoap11"), ConectorUnicoPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConectorUnicoPort
     */
    @WebEndpoint(name = "ConectorUnicoPortSoap11")
    public ConectorUnicoPort getConectorUnicoPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://conectorunico.com.mx/definitions", "ConectorUnicoPortSoap11"), ConectorUnicoPort.class, features);
    }

}
