package com.elektra.uniformes.comercio.cron.dao.clienteWS.DescuentosSap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Srv_DescSoap", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SrvDescSoap {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.tempuri.EmpCargaDescUniformeResponse
     */
    @WebMethod(operationName = "Emp_Carga_Desc_Uniforme", action = "http://tempuri.org/Emp_Carga_Desc_Uniforme")
    @WebResult(name = "Emp_Carga_Desc_UniformeResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public EmpCargaDescUniformeResponse empCargaDescUniforme(
        @WebParam(name = "Emp_Carga_Desc_Uniforme", targetNamespace = "http://tempuri.org/", partName = "parameters")
        EmpCargaDescUniforme parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.tempuri.EmpCargaDescUniformeGTResponse
     */
    @WebMethod(operationName = "Emp_Carga_Desc_Uniforme_GT", action = "http://tempuri.org/Emp_Carga_Desc_Uniforme_GT")
    @WebResult(name = "Emp_Carga_Desc_Uniforme_GTResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public EmpCargaDescUniformeGTResponse empCargaDescUniformeGT(
        @WebParam(name = "Emp_Carga_Desc_Uniforme_GT", targetNamespace = "http://tempuri.org/", partName = "parameters")
        EmpCargaDescUniformeGT parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.tempuri.EmpCargaDescGafeteResponse
     */
    @WebMethod(operationName = "Emp_Carga_Desc_Gafete", action = "http://tempuri.org/Emp_Carga_Desc_Gafete")
    @WebResult(name = "Emp_Carga_Desc_GafeteResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public EmpCargaDescGafeteResponse empCargaDescGafete(
        @WebParam(name = "Emp_Carga_Desc_Gafete", targetNamespace = "http://tempuri.org/", partName = "parameters")
        EmpCargaDescGafete parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.tempuri.EmpCargaDescTarjValDespResponse
     */
    @WebMethod(operationName = "Emp_Carga_Desc_Tarj_ValDesp", action = "http://tempuri.org/Emp_Carga_Desc_Tarj_ValDesp")
    @WebResult(name = "Emp_Carga_Desc_Tarj_ValDespResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public EmpCargaDescTarjValDespResponse empCargaDescTarjValDesp(
        @WebParam(name = "Emp_Carga_Desc_Tarj_ValDesp", targetNamespace = "http://tempuri.org/", partName = "parameters")
        EmpCargaDescTarjValDesp parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.tempuri.EmpCargaDescTelefoniaResponse
     */
    @WebMethod(operationName = "Emp_Carga_Desc_Telefonia", action = "http://tempuri.org/Emp_Carga_Desc_Telefonia")
    @WebResult(name = "Emp_Carga_Desc_TelefoniaResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public EmpCargaDescTelefoniaResponse empCargaDescTelefonia(
        @WebParam(name = "Emp_Carga_Desc_Telefonia", targetNamespace = "http://tempuri.org/", partName = "parameters")
        EmpCargaDescTelefonia parameters);

}
