
package com.elektra.uniformes.comercio.cron.dao.clienteWS.Token;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GeneraTokenPortService", targetNamespace = "http://generatoken.com.mx/definitions", wsdlLocation = "file:/V:/CENTRALdesarrollo_view/desCentralC3/Aplicaciones/UnifOperacion/SRVUniformesComercio/Fuente/DAO/src/main/java/com/elektra/uniformes/comercio/cron/dao/clienteWS/WS_Token.wsdl")
public class GeneraTokenPortService
    extends Service
{

    private final static URL GENERATOKENPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.elektra.uniformes.comercio.cron.dao.clienteWS.Token.GeneraTokenPortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.elektra.uniformes.comercio.cron.dao.clienteWS.Token.GeneraTokenPortService.class.getResource(".");
            url = new URL(baseUrl, "file:/V:/CENTRALdesarrollo_view/desCentralC3/Aplicaciones/UnifOperacion/SRVUniformesComercio/Fuente/DAO/src/main/java/com/elektra/uniformes/comercio/cron/dao/clienteWS/WS_Token.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/V:/CENTRALdesarrollo_view/desCentralC3/Aplicaciones/UnifOperacion/SRVUniformesComercio/Fuente/DAO/src/main/java/com/elektra/uniformes/comercio/cron/dao/clienteWS/WS_Token.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GENERATOKENPORTSERVICE_WSDL_LOCATION = url;
    }

    public GeneraTokenPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneraTokenPortService() {
        super(GENERATOKENPORTSERVICE_WSDL_LOCATION, new QName("http://generatoken.com.mx/definitions", "GeneraTokenPortService"));
    }

    /**
     * 
     * @return
     *     returns GeneraTokenPort
     */
    @WebEndpoint(name = "GeneraTokenPortSoap11")
    public GeneraTokenPort getGeneraTokenPortSoap11() {
        return super.getPort(new QName("http://generatoken.com.mx/definitions", "GeneraTokenPortSoap11"), GeneraTokenPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneraTokenPort
     */
    @WebEndpoint(name = "GeneraTokenPortSoap11")
    public GeneraTokenPort getGeneraTokenPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://generatoken.com.mx/definitions", "GeneraTokenPortSoap11"), GeneraTokenPort.class, features);
    }

}
