
package com.elektra.uniformes.comercio.cron.dao.clienteWS.ConsultaCDXTiendas;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "intfGET_Inventario-service", targetNamespace = "http://xmlns.example.com/1404945899682", wsdlLocation = "file:/V:/CENTRALdesarrollo_view/desCentralC3/Aplicaciones/UnifOperacion/SRVUniformesComercio/Fuente/DAO/src/main/java/com/elektra/uniformes/comercio/cron/dao/clienteWS/WS_M_CATALOG_TDA.wsdl")
public class IntfGETInventarioService
    extends Service
{

    private final static URL INTFGETINVENTARIOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.elektra.uniformes.comercio.cron.dao.clienteWS.ConsultaCDXTiendas.IntfGETInventarioService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.elektra.uniformes.comercio.cron.dao.clienteWS.ConsultaCDXTiendas.IntfGETInventarioService.class.getResource(".");
            url = new URL(baseUrl, "file:/V:/CENTRALdesarrollo_view/desCentralC3/Aplicaciones/UnifOperacion/SRVUniformesComercio/Fuente/DAO/src/main/java/com/elektra/uniformes/comercio/cron/dao/clienteWS/WS_M_CATALOG_TDA.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/V:/CENTRALdesarrollo_view/desCentralC3/Aplicaciones/UnifOperacion/SRVUniformesComercio/Fuente/DAO/src/main/java/com/elektra/uniformes/comercio/cron/dao/clienteWS/WS_M_CATALOG_TDA.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTFGETINVENTARIOSERVICE_WSDL_LOCATION = url;
    }

    public IntfGETInventarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntfGETInventarioService() {
        super(INTFGETINVENTARIOSERVICE_WSDL_LOCATION, new QName("http://xmlns.example.com/1404945899682", "intfGET_Inventario-service"));
    }

    /**
     * 
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "intfwsGET_InventarioEndpoint0")
    public PortType getIntfwsGETInventarioEndpoint0() {
        return super.getPort(new QName("http://xmlns.example.com/1404945899682", "intfwsGET_InventarioEndpoint0"), PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortType
     */
    @WebEndpoint(name = "intfwsGET_InventarioEndpoint0")
    public PortType getIntfwsGETInventarioEndpoint0(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1404945899682", "intfwsGET_InventarioEndpoint0"), PortType.class, features);
    }

}
