
package com.elektra.uniformes.comercio.cron.dao.clienteWS.ConsultaCDXTiendas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "portType", targetNamespace = "http://xmlns.example.com/1404945899682")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns ConsultaCDXTiendas.TSalida
     */
    @WebMethod(operationName = "GET__InventarioOp", action = "/BussinesProcesses/System/WSEvents/intfGET_Inventario-service.serviceagent/intfwsGET_InventarioEndpoint1/GET__InventarioOp")
    @WebResult(name = "T_Salida", targetNamespace = "http://www.tibco.com/schemas/WS_M_CATALOG_TDA/SharedResources/SchemaDefinitions/Custom/EKT/Schema.xsd2", partName = "parameters")
    public TSalida getInventarioOp(
        @WebParam(name = "Parametro", targetNamespace = "http://www.tibco.com/schemas/WS_M_CATALOG_TDA/SharedResources/SchemaDefinitions/Custom/EKT/Schema.xsd", partName = "parameters")
        Parametro parameters);

}
